### PR TITLE
fix(ssl): add an openssl is linked / loadable by lua test refs: #FT-3364

### PR DESCRIPTION
**Pull request by hutchic**
Related to https://github.com/Kong/kong-ee/pull/3795 added a quick and dirty test so we don't regress

### CODE REVIEW

**Review by flrgh — APPROVED** [review]

**Comment by hutchic** [comment]
I expect this to fail and we shouldn't merge until after https://github.com/Kong/kong-ee/pull/3796

**Review by gszr — APPROVED** [review]

**Comment by tyler-ball** [comment]
Rebased in order to re-run the tests now that https://github.com/Kong/kong-ee/pull/3795 is merged

**Comment by curiositycasualty** [comment]
👍

**Comment by curiositycasualty** [comment]
Hmm, it's unclear why this merged :/
I did enable automerge back in september, but I don't see a single green run in Jenkins for this PR.

**Pull request merged**
