### PR TITLE
Adding more details to README

### PR DESCRIPTION
**Pull request by Hayk-S**

### CODE REVIEW

**Review by curiositycasualty — APPROVED** [review]

**Comment by curiositycasualty** [comment]
Actually, @Hayk-S Can I get you to format this commit as a semantic one?
It would look something like: `chore(docs): adding more details to README`

This repo uses the semantic release action to determine how/what to release automagically: https://github.com/Kong/kong-build-tools/blob/master/.github/workflows/release.yaml#L17-L21

**Comment by Hayk-S** [comment]
@curiositycasualty can you please check now?

**Comment by curiositycasualty** [comment]
@Hayk-S Looks good to me. Automerge enabled.

**Comment by Hayk-S** [comment]
Thanks @curiositycasualty

**Pull request merged**
