### PR TITLE
chore(patches) add kong patches for openresty 1.19.3.1

### PR DESCRIPTION
**Pull request by bungle**
### Summary

Adds adjusted Kong patches for OpenResty 1.19.3.1 release.

### CODE REVIEW

**Comment by hutchic** [comment]
friendly reminder: kong-build-tools tests by building kong@next (per [here](https://github.com/Kong/kong-build-tools/blob/master/Jenkinsfile#L7)) so the new patches won't actually be exercised by CI. The CI in this case ensures that the changes are compatible with what's running on kong@next

To test the new patch with the new openresty version your options are

You could `export RESTY_VERSION=1.19.3.1` in the KBT Jenkinsfile (remove it prior to merging -- I've never tried this way but in theory it should work) or
You could open a Kong PR that adjusts [RESTY_VERSION](https://github.com/Kong/kong/blob/master/.requirements#L5) and [KONG_BUILD_TOOLS](https://github.com/Kong/kong/blob/master/Makefile#L31)

**Comment by hutchic** [comment]
The same test failed in an identical way on retry. May need to be investigated
image

**Review by dndx — COMMENTED** [review]
Minor question. Also, did we remove `LuaJIT-2.1-20200102_01-dyn-lightuserdata-map.patch` intentionally? The rest of patches removed LGTM.

**Comment by javierguerragiraldez** [comment]
> did we remove `LuaJIT-2.1-20200102_01-dyn-lightuserdata-map.patch` intentionally?

yes, the latest LuaJIT makes lightuserdata full 64bit transparent.

**Review by dndx — APPROVED** [review]

**Pull request merged**
